name: Deploy para VM Local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64] # Roda na própria VM!
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    
    - name: Atualizar site
      run: |
        cd /var/www/html
        sudo git fetch origin main
        sudo git reset --hard origin/main
        sudo git clean -fd
    
        sudo systemctl restart nginx
        echo "✅ Deploy realizado com sucesso em $(date)"
